"""push

Revision ID: ad2fcfe74f80
Revises: a9c62b75a999
Create Date: 2023-03-20 19:58:51.432429

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ad2fcfe74f80"
down_revision = "a9c62b75a999"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
